### ISSUE TITLE
单页面存在多个组件,方法在页面渲染时调用

### ISSUE THREAD

**Issue by l2394251881** [yz-flying/Extend-Element#1]
1.单页面存在多个组件.首次进入每个组件方法都会调用.可优化
2.tabs切换first会进行一次方法调用
3.查询css可优化.上下间隔问题
4.组件分页考虑放在table右侧

**Comment by l2394251881** [comment]
2 解决

**Comment by OneGs** [comment]
1. 第一点组件内部无法识别多组实例，也不应该根据多组实例判断而阻止同时请求。（会影响整个页面的数据加载）
2. 没太懂什么意思
3. 问题解决
4. 提供一个position选项，[right left center]三种选项。
