### ISSUE TITLE
一些bug

### ISSUE THREAD

**Issue by ZhangZhiQiang8** [yz-flying/Extend-Element#2]
1.重置点击第一次只会重置表单不会更新数据 第二次才会
2.用插槽新增的搜索框按钮和表格位置永远在最前面
3.搜索框和表格的样式需要优化

**Comment by OneGs** [comment]
1. 解决
2. 放到后面去了
3. 问题解决

**Comment by OneGs** [comment]
1. 解决
2. 放到后面去了
3. 问题解决
